name: Create Repository

on:
  issues:
    types: 
      - opened
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'repo-creation')
    steps:
      - uses: actions/checkout@v3

      ## validate the deetz
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/repo_creation.yaml
      
      # Don't run if a field is empty
      - name: Test variables
        run: |
          if [[ -z "${{ steps.issue-parser.outputs.issueparser_repo-name }}" || -z "${{ steps.issue-parser.outputs.issueparser_template }}" ]] \
            || -z "${{ steps.issue-parser.outputs.issueparser_branch-name }}" ]]; then
            echo Please submit a new issue and fill out ALL the fields
            exit 1
          fi
          ## Todo write this to the issue, maybe allow a /rerun command

      # Check if repo by the name already exists and notify in issue/exit if it does
      - name: Checking for repo existance
        id: checkRepo
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          if gh api /repos/${{ github.repository_owner }}/${{ steps.issue-parser.outputs.issueparser_repo-name }} > /dev/null 2>&1; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create the repository
        id: createRepo
        continue-on-error: true
        if: steps.checkRepo.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          # do this https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-using-a-template
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ steps.issue-parser.outputs.issueparser_template }}/generate \
            -f owner='${{ github.repository_owner }}' \
            -f name='${{ steps.issue-parser.outputs.issueparser_repo-name }}' \
            -f description='This a generated repo' \
            -F include_all_branches=true \
            -F private=true

      - name: Comment success on repository creation
        if: steps.createRepo.outcome == 'success' && steps.checkRepo.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh issue comment ${{ github.event.issue.number }} \
            --body "The repository ${{ steps.issue-parser.outputs.issueparser_repo-name }} has been successfully created."

      - name: Comment failure on repository creation
        if: steps.createRepo.outcome == 'failure' && steps.checkRepo.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh issue comment ${{ github.event.issue.number }} \
            --body "There was an error creating the repository ${{ steps.issue-parser.outputs.issueparser_repo-name }}. Please try again."

      - name: Add user as an admin of the repository
        id: addUserAsAdmin
        if: steps.createRepo.outcome == 'success' && steps.checkRepo.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh api -X PUT /repos/${{ github.repository_owner }}/${{ steps.issue-parser.outputs.issueparser_repo-name }}/collaborators/${{ github.event.issue.user.login }} -f permission=admin

      - name: Comment success adding user as admin
        if: steps.addUserAsAdmin.outcome == 'success' && steps.checkRepo.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh issue comment ${{ github.event.issue.number }} \
            --body "The user ${{ github.event.issue.user.login }} was successsfully added as an admin of the repository"
  
      - name: Comment failure on adding user as admin
        if: steps.addUserAsAdmin.outcome == 'failure' && steps.checkRepo.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh issue comment ${{ github.event.issue.number }} \
            --body "There was an error adding user ${{ github.event.issue.user.login }} as an admin of the repository. Please try again."    

      - name: TODO Add users/teams permissions to repo
        if: steps.createRepo.outcome == 'success'
        run: |
          # Comment back to issue & close issue. Add Github.actor as admin, add teams specified
          echo "teams todo"
  
      - name: Close issue
        if: steps.createRepo.outcome == 'success'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh issue close ${{ github.event.issue.number }}
  